service: mountain-ui-api
frameworkVersion: "3"

plugins:
  - serverless-prune-plugin
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline-ses
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  serverlessPluginTypescript:
    tsConfigFileLocation: "./tsconfig.lambda.json"
  dynamodb:
    stages:
      - ${opt:stage, self:provider.stage}
    start:
      port: 8080
      inMemory: false
      migrate: true
  serverless-offline:
    httpPort: 8000
    websocketPort: 8001
    lambdaPort: 8002
    useWorkerThreads: true
  ses:
    stages:
      - dev
    clean: true
    outputDir: "./.build/ses_output"

package:
  patterns:
    - schema.graphql

provider:
  name: aws
  stage: dev
  region: us-west-1
  runtime: nodejs18.x
  memorySize: 512
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource:
            - arn:aws:s3:::mountain-ui-app-slopes-unzipped
            - arn:aws:s3:::mountain-ui-app-slopes-unzipped/*
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - arn:aws:dynamodb:*:${env:AWS_ACCOUNT_ID}:table/mountain-ui-app-users
            - arn:aws:dynamodb:*:${env:AWS_ACCOUNT_ID}:table/mountain-ui-app-users/index/*

functions:
  graphql:
    description: GraphQL API
    handler: ./src/index.handler
    events:
      - http:
          path: /graphql
          method: post
          cors: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: mountain-ui-app-users
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: appleId
            AttributeType: S
          - AttributeName: googleId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: appleId
            KeySchema:
              - AttributeName: appleId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: googleId
            KeySchema:
              - AttributeName: googleId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
