service: mountain-ui-slopes-unzipper
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 256
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource:
            - arn:aws:s3:::mountain-ui-app-slopes-zipped
            - arn:aws:s3:::mountain-ui-app-slopes-zipped/*
        - Effect: Allow
          Action:
            - s3:PutObject
          Resource:
            - arn:aws:s3:::mountain-ui-app-slopes-unzipped
            - arn:aws:s3:::mountain-ui-app-slopes-unzipped/*

functions:
  mountain-ui-unzipper:
    handler: index.handler
    events:
      - s3: mountain-ui-app-slopes-zipped

plugins:
  - serverless-plugin-typescript

resources:
  Resources:
    MountainUISlopesUnzippedBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: mountain-ui-app-slopes-unzipped
