service: lynx-slopes-unzipper
frameworkVersion: "3"

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  stage: dev
  region: us-west-1
  runtime: nodejs18.x
  memorySize: 1024
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource:
            - arn:aws:s3:::lynx-slopes-zipped
            - arn:aws:s3:::lynx-slopes-zipped/*
        - Effect: Allow
          Action:
            - s3:PutObject
          Resource:
            - arn:aws:s3:::lynx-slopes-unzipped
            - arn:aws:s3:::lynx-slopes-unzipped/*

functions:
  lynx-unzipper:
    handler: index.handler
    events:
      - s3: lynx-slopes-zipped

plugins:
  - serverless-plugin-typescript

resources:
  Resources:
    MountainUISlopesUnzippedBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: lynx-slopes-unzipped
        OwnershipControls:
          Rules:
            - ObjectOwnership: BucketOwnerEnforced
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
