service: lynx-api
frameworkVersion: "3"

plugins:
  - serverless-prune-plugin
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline-ses
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  serverlessPluginTypescript:
    tsConfigFileLocation: "./tsconfig.lambda.json"
  dynamodb:
    stages:
      - ${opt:stage, self:provider.stage}
    start:
      port: 8080
      inMemory: false
      migrate: true
  serverless-offline:
    httpPort: 8000
    websocketPort: 8001
    lambdaPort: 8002
    useWorkerThreads: true
  ses:
    stages:
      - dev
    clean: true
    outputDir: "./.build/ses_output"

package:
  patterns:
    - schema.graphql

provider:
  name: aws
  stage: dev
  region: us-west-1
  runtime: nodejs18.x
  memorySize: 1024
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:ListBucket
            - s3:GetObject
            - s3:DeleteObject
          Resource:
            - arn:aws:s3:::lynx-slopes-unzipped
            - arn:aws:s3:::lynx-slopes-unzipped/*
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:DeleteObject
          Resource:
            - arn:aws:s3:::lynx-slopes-zipped
            - arn:aws:s3:::lynx-slopes-zipped/*
        - Effect: Allow
          Action: 
            - s3:ListBucket
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
          Resource:
            - arn:aws:s3:::lynx-profile-pictures
            - arn:aws:s3:::lynx-profile-pictures/*
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:DeleteItem
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:UpdateItem
          Resource:
            # - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/lynx-users
            # - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/lynx-users/index/*
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:DeleteItem
            - dynamodb:PutItem
            - dynamodb:Query
          Resource:
            # - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/lynx-invites
       
functions:
  graphql:
    description: GraphQL API
    handler: ./src/index.handler
    events:
      - http:
          path: /graphql
          method: post
          cors: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: lynx-users
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: appleId
            AttributeType: S
          - AttributeName: googleId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: appleId
            KeySchema:
              - AttributeName: appleId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: googleId
            KeySchema:
              - AttributeName: googleId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
    inviteTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: lynx-invites
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

    MountainUIProfilePictureBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: lynx-profile-pictures
        OwnershipControls:
          Rules:
            - ObjectOwnership: BucketOwnerEnforced
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
    MountainUIProfilePictureBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: lynx-profile-pictures
        PolicyDocument:
          Statement:
            - Action:
                - s3:GetObject
              Effect: Allow
              Resource:
                - arn:aws:s3:::lynx-profile-pictures/*
              Principal: "*"
