name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:

  deploy-serverless:
    
    name: Deploy AWS Lambdas Via Serverless
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Cache Node Modules
        uses: actions/cache@v3
        id: cache
        with:
          path: lynx-api/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Node Modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install --prefix lynx-api

      - name: Create Lynx .env File
        uses: iamsauravsharma/create-dotenv@v2.0.1
        with:
          file-path: 'lynx-api/.env'
        env:
          APPLE_CLIENT_ID: ${{ secrets.APPLE_CLIENT_ID }}
          APPLE_CLIENT_SECRET: ${{ secrets.APPLE_CLIENT_SECRET }}
          AUTH_KEY: ${{ secrets.AUTH_KEY }}
          ESCAPE_INVITE_HATCH: ${{ secrets.ESCAPE_INVITE_HATCH }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          NODE_ENV: "production"

      - name: Deploy
        run: npm run --prefix lynx-api deploy
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
